// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZaehfgWkK2llidFkm8_Tr4AssXgSqzpw',
    appId: '1:629208044486:web:28b329220360e5ddefd8c7',
    messagingSenderId: '629208044486',
    projectId: 'naukri-blogg',
    authDomain: 'naukri-blogg.firebaseapp.com',
    databaseURL:'https://naukri-blogg-default-rtdb.firebaseio.com',
    storageBucket: 'naukri-blogg.appspot.com',
    measurementId: 'G-RMGP6FR2X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYm2lEPu0-01j4pFrQsCo8RoB2Ju3MTQk',
    appId: '1:629208044486:android:06c0dad67bde4163efd8c7',
    messagingSenderId: '629208044486',
   // databaseURL:'https://naukri-blogg-default-rtdb.firebaseio.com',
    projectId: 'naukri-blogg',
    storageBucket: 'naukri-blogg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3W05MJybWr9iOp2ZTfJ1GgCheFXqsYiw',
    appId: '1:629208044486:ios:1b8792c37507f044efd8c7',
    messagingSenderId: '629208044486',
    projectId: 'naukri-blogg',
   // databaseURL:'https://naukri-blogg-default-rtdb.firebaseio.com',
    storageBucket: 'naukri-blogg.appspot.com',
    iosBundleId: 'com.example.naukriBloggs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3W05MJybWr9iOp2ZTfJ1GgCheFXqsYiw',
    appId: '1:629208044486:ios:1b8792c37507f044efd8c7',
    messagingSenderId: '629208044486',
    projectId: 'naukri-blogg',
   // databaseURL:'https://naukri-blogg-default-rtdb.firebaseio.com',
    storageBucket: 'naukri-blogg.appspot.com',
    iosBundleId: 'com.example.naukriBloggs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZaehfgWkK2llidFkm8_Tr4AssXgSqzpw',
    appId: '1:629208044486:web:4fff6049e64b9f44efd8c7',
    messagingSenderId: '629208044486',
    projectId: 'naukri-blogg',
    databaseURL:'https://naukri-blogg-default-rtdb.firebaseio.com',
    authDomain: 'naukri-blogg.firebaseapp.com',
    storageBucket: 'naukri-blogg.appspot.com',
    measurementId: 'G-5G964T0ZP3',
  );
}
